### PR TITLE
Plat 545

### PR DESCRIPTION
**Pull request by mbarcia**

### CODE REVIEW

**Comment by pobtastic** [comment]
I'd rather not merge this, I don't know why we'd want to make this move?  I'd like to see the ticket which prompted this reasoning.

If we are to get rid of memcache, then simply upgrading to PHP7.x which provide an adequate speed increase in order to do so (without having to bring anything else in).  Drupal 7 is compliant already, the only things which may require updating would be custom theme/ module files, but the changes are quite simple to do.

**Comment by marcinmaruszewski** [comment]
Hi @pobtastic, please be noted that we are using this branch on Miss Sporty live website. 
https://github.com/cotyinc/www.miss-sporty.com/blob/master/ansible/requirements.yml#L16

**Comment by pobtastic** [comment]
Great, can you point me to a conversion/ ticket where it was discussed that this would be necessary?

**Comment by marcinmaruszewski** [comment]
@pobtastic, I'm afraid that's all what I have found - https://beamly.slack.com/archives/C1VUV53D4/p1515064250000407?thread_ts=1515062506.000029&cid=C1VUV53D4

**Comment by pobtastic** [comment]
Closing due to nonsense.  Not deleting due to production sites using this branch, will clean up later...

**Pull request closed without merging**
